### ISSUE TITLE
找不到R.java

### ISSUE THREAD

**Issue by spianmo** [7hens/android-x2j#2]
多渠道下R.java不在ap_generated_sources文件夹，在not_namespaced_r_class_sources文件夹

**Comment by 7hens** [comment]
这是因为 [x2c  本身找不到 R 文件](https://github.com/iReaderAndroid/X2C/issues/37)。
根本原因在于 x2c 的核心功能是基于 apt 的，而在 apt 里面获取到的 R 文件都是不准确的。

android-x2j 目前通过一种方法弥补了 x2c 的这一缺陷：

1. 利用 android-x2j 来找到 R 文件
2. 利用这个 R 文件，来生成第二个 R 文件，取名为 X2J_R.java
3. 然后 X2C 再来读取 X2J_R.java

首先第一步，利用 android-x2j 来找到 R 文件。
这一步可以保证能够准确的获取到 R 文件。
因为在 gradle 里获取 R  要比 apt 中靠谱得多。
这里有另一个问题，library 工程里不会生成 R.java（也许只有新版的 gradle 才会这样？），
但是取而代之，有一个类似的文件 R.txt，功能和 R.java 类似，也可凑合着用。

第二步，利用这个 R 文件（R.java 或 R.txt），来生成第二个 R 文件，取名为 X2J_R.java。
这里为什么要生成第二个 R 文件？是为了兼容 library。
library 打出的 jar/aar 包是不带 R 文件的。
为了防止命名冲突，将新的 R 文件取名为 X2J_R.java
（本来想取名 R2.java 的，好像被 Butterknife 先用了...）

第三步，X2C 读取 X2J_R.java。
因为 X2J_R.java 的生成目录是固定的，所以可以很简单的就获取到这个 R。

以上就是 android-x2j 最新版 1.4 更新的内容。
