### ISSUE TITLE
需要支持 layout xml 输入可配置

### ISSUE THREAD

**Issue by 7hens** [7hens/android-x2j#5]
android-x2j 目前会将所有的 xml 都翻译并注入到 java 字节码里。
考虑后期加个配置项，让开发者决定哪些 xml 需要被注入。

**Comment by linge123** [comment]
目前支持吗？

**Comment by 7hens** [comment]
@linge123 暂不支持，后面会考虑加上

**Comment by 7hens** [comment]
@linge123 新版的 v1.5 已经支持 xml 布局自定义了，支持使用正则匹配的 includes 和 excludes。v1.5 同时还适配了新版本的 gradle。
